package com.jbzhang.ws.cxfclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-04-12T13:03:45.253+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://cxfserver.ws.jbzhang.com/", name = "HelloMyFirstService")
public interface HelloMyFirstService {

    @WebMethod(operationName = "Hello")
    @RequestWrapper(localName = "Hello", targetNamespace = "http://cxfserver.ws.jbzhang.com/", className = "com.jbzhang.ws.cxfclient.Hello")
    @ResponseWrapper(localName = "HelloResponse", targetNamespace = "http://cxfserver.ws.jbzhang.com/", className = "com.jbzhang.ws.cxfclient.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
