
package com.jbzhang.ws.jdkserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloMyFirstServiceImpl", targetNamespace = "http://jdkserver.ws.jbzhang.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloMyFirstServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloService", targetNamespace = "http://jdkserver.ws.jbzhang.com/", className = "com.jbzhang.ws.jdkserver.HelloService")
    @ResponseWrapper(localName = "helloServiceResponse", targetNamespace = "http://jdkserver.ws.jbzhang.com/", className = "com.jbzhang.ws.jdkserver.HelloServiceResponse")
    @Action(input = "http://jdkserver.ws.jbzhang.com/HelloMyFirstServiceImpl/helloServiceRequest", output = "http://jdkserver.ws.jbzhang.com/HelloMyFirstServiceImpl/helloServiceResponse")
    public String helloService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
